set -e
true
true
/home/hphuc/SPAdes-3.15.5/bin/spades-hammer /home/hphuc/hphuc_miniproject_organelleseq/tool/getorganelle/extended_spades/corrected/configs/config.info
/home/hphuc/anaconda3/envs/getorganelle/bin/python /home/hphuc/SPAdes-3.15.5/share/spades/spades_pipeline/scripts/compress_all.py --input_file /home/hphuc/hphuc_miniproject_organelleseq/tool/getorganelle/extended_spades/corrected/corrected.yaml --ext_python_modules_home /home/hphuc/SPAdes-3.15.5/share/spades --max_threads 1 --output_dir /home/hphuc/hphuc_miniproject_organelleseq/tool/getorganelle/extended_spades/corrected --gzip_output
true
true
/home/hphuc/SPAdes-3.15.5/bin/spades-core /home/hphuc/hphuc_miniproject_organelleseq/tool/getorganelle/extended_spades/K21/configs/config.info
/home/hphuc/SPAdes-3.15.5/bin/spades-core /home/hphuc/hphuc_miniproject_organelleseq/tool/getorganelle/extended_spades/K55/configs/config.info
/home/hphuc/SPAdes-3.15.5/bin/spades-core /home/hphuc/hphuc_miniproject_organelleseq/tool/getorganelle/extended_spades/K85/configs/config.info
/home/hphuc/anaconda3/envs/getorganelle/bin/python /home/hphuc/SPAdes-3.15.5/share/spades/spades_pipeline/scripts/copy_files.py /home/hphuc/hphuc_miniproject_organelleseq/tool/getorganelle/extended_spades/K85/before_rr.fasta /home/hphuc/hphuc_miniproject_organelleseq/tool/getorganelle/extended_spades/before_rr.fasta /home/hphuc/hphuc_miniproject_organelleseq/tool/getorganelle/extended_spades/K85/assembly_graph_after_simplification.gfa /home/hphuc/hphuc_miniproject_organelleseq/tool/getorganelle/extended_spades/assembly_graph_after_simplification.gfa /home/hphuc/hphuc_miniproject_organelleseq/tool/getorganelle/extended_spades/K85/final_contigs.fasta /home/hphuc/hphuc_miniproject_organelleseq/tool/getorganelle/extended_spades/contigs.fasta /home/hphuc/hphuc_miniproject_organelleseq/tool/getorganelle/extended_spades/K85/first_pe_contigs.fasta /home/hphuc/hphuc_miniproject_organelleseq/tool/getorganelle/extended_spades/first_pe_contigs.fasta /home/hphuc/hphuc_miniproject_organelleseq/tool/getorganelle/extended_spades/K85/strain_graph.gfa /home/hphuc/hphuc_miniproject_organelleseq/tool/getorganelle/extended_spades/strain_graph.gfa /home/hphuc/hphuc_miniproject_organelleseq/tool/getorganelle/extended_spades/K85/scaffolds.fasta /home/hphuc/hphuc_miniproject_organelleseq/tool/getorganelle/extended_spades/scaffolds.fasta /home/hphuc/hphuc_miniproject_organelleseq/tool/getorganelle/extended_spades/K85/scaffolds.paths /home/hphuc/hphuc_miniproject_organelleseq/tool/getorganelle/extended_spades/scaffolds.paths /home/hphuc/hphuc_miniproject_organelleseq/tool/getorganelle/extended_spades/K85/assembly_graph_with_scaffolds.gfa /home/hphuc/hphuc_miniproject_organelleseq/tool/getorganelle/extended_spades/assembly_graph_with_scaffolds.gfa /home/hphuc/hphuc_miniproject_organelleseq/tool/getorganelle/extended_spades/K85/assembly_graph.fastg /home/hphuc/hphuc_miniproject_organelleseq/tool/getorganelle/extended_spades/assembly_graph.fastg /home/hphuc/hphuc_miniproject_organelleseq/tool/getorganelle/extended_spades/K85/final_contigs.paths /home/hphuc/hphuc_miniproject_organelleseq/tool/getorganelle/extended_spades/contigs.paths
true
/home/hphuc/anaconda3/envs/getorganelle/bin/python /home/hphuc/SPAdes-3.15.5/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /home/hphuc/hphuc_miniproject_organelleseq/tool/getorganelle/extended_spades/scaffolds.fasta --misc_dir /home/hphuc/hphuc_miniproject_organelleseq/tool/getorganelle/extended_spades/misc --threshold_for_breaking_scaffolds 3
true
